import { ClientProvider } from "~/utils/trpc";
import { type AppType } from "next/app";
import "~/styles/globals.css";
import Head from "next/head";
import { type PropsWithChildren } from "react";

const MyApp: AppType = (props: PropsWithChildren) => {
  return (
    <html>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <main className="flex min-h-screen flex-col items-center justify-center ">
          <ClientProvider>{props.children}</ClientProvider>
        </main>
      </body>
    </html>
  );
};

export default MyApp;
